=== walasiek/hipisejm/resources/hipisejm-transcript-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0.0">

  <xs:element name="session" type="sessionType"/>

  <!-- Root Element Definition -->
  <xs:complexType name="sessionType">
      <xs:sequence>
        <xs:element name="meta" type="metaType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="session_officials" type="officialsType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="content" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element name="speech" type="speechType"/>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="source" type="xs:string" use="optional"/>
  </xs:complexType>

  <!-- Meta params -->
  <xs:complexType name="metaType">
    <xs:sequence>
      <xs:element name="session_no" minOccurs="1" maxOccurs="1">
      </xs:element>
      <xs:element name="term_no" minOccurs="1" maxOccurs="1">
      </xs:element>
      <xs:element name="session_date" minOccurs="1" maxOccurs="1">
      </xs:element>
    </xs:sequence>
  </xs:complexType>


  <!-- Session Officials -->
  <xs:complexType name="officialsType">
    <xs:sequence>
      <xs:element name="official" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="title" type="xs:string" use="required"/>
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Speech Type -->
  <xs:complexType name="speechType">
    <xs:sequence>
      <xs:element name="utt" minOccurs="0" maxOccurs="unbounded" type="uttType"/>
    </xs:sequence>
    <xs:attribute name="speaker" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Utterance Type -->
  <xs:complexType name="uttType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <!-- t (type) refers to one of the:
             - norm (regular speech of the speaker)
             - reaction (reaction from the audience)
             - interrupt (interruption by someone from the audience) -->
        <xs:attribute type="xs:string" name="t" use="required"/>
        <xs:attribute type="xs:string" name="by" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== walasiek/hipisejm/resources/hipisejm-transcript-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<session xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="hipisejm-transcript-schema.xsd"
         source="filename_from_which_file_was_created.pdf">

  <meta>
    <session_no>1</session_no>
    <term_no>10</term_no>
    <session_date>2023-12-12</session_date>
  </meta>
  <session_officials>
    <official title="speaker" name="Szymon Hołownia"/>
    <official title="vice_speaker" name="Monika Wielichowska"/>
    <!-- Additional officials -->
  </session_officials>
  <content>
    <speech speaker="Marszałek Szymon Hołownia">
      <utt t="norm">What has the speaker said...</utt>
      <utt t="interrupt" by="Someone from the audience">Someone interrupts here...</utt>
      <utt t="norm">...speaker tries to continue...</utt>
      <utt t="reaction">Reaction from the audience</utt>
      <utt t="norm">...speaker finishes.</utt>
      <!-- Continuation of the speech by Jan Kowalski -->
    </speech>
    <!-- Next speeches of other persons -->
  </content>
</session>

=== walasiek/hipisejm/resources/test_data/parsed-01_j_ksiazka-part.xml
<?xml version="1.0" encoding="UTF-8"?>
<session xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="hipisejm-transcript-schema.xsd" source="01_j_ksiazka.pdf">
<meta>
<session_no>1</session_no>
<term_no>10</term_no>
<session_date>2023-12-12</session_date>
</meta>
<session_officials>
<official title="speaker" name="Szymon Hołownia"/>
<official title="vice_speaker" name="Monika Wielichowska"/>
<official title="vice_speaker" name="Włodzimierz Czarzasty"/>
<official title="vice_speaker" name="Krzysztof Bosak"/>
<official title="vice_speaker" name="Piotr Zgorzelski"/>
<official title="vice_speaker" name="Dorota Niedziela"/>
</session_officials>
<content>
<speech speaker="Marszałek Szymon Hołownia">
<utt t="norm">Szanowni Państwo! Opóźniam trochę wznowienie posiedzenia, dlatego że widzę, jak długa kolejka posłów chcących zapisać się do pytań po exposé ustawiła się tutaj. Dam jeszcze na to kilka minut, bo nie chciałbym, żebyście państwo dezorganizowali tu pracę. Jak już powitam gości, poproszę o to, żebyście zajęli miejsca i wrócili później. Lista posłów zgłoszonych do pytań nie będzie zamknięta aż do momentu, kiedy skończą się oświadczenia w imieniu klubów i kół, tak że pewnie to jeszcze potrwa jakieś 2, 3 godziny. Na pewno każdy będzie mógł się zapisać do zadania pytania. Pytania dzisiaj nie są w żaden sposób limitowane.</utt>
<utt t="reaction">Wypowiedź poza mikrofonem</utt>
<utt t="norm">Jeszcze raz, bo nie słyszę.</utt>
<utt t="reaction">Wypowiedź poza mikrofonem</utt>
<utt t="norm">Czasowo będą limitowane, absolutnie, tak jak zawsze.</utt>
<utt t="interrupt" by="Głos z sali">Sprzeciw!</utt>
<utt t="norm">Słyszę sprzeciw. Zaraz będziemy głosować. Spokojnie, kochani państwo, wszystko po kolei.</utt>
<utt t="reaction">Chwila przerwy</utt>
<utt t="norm">Szanowni Państwo! Za 4 minuty zaczynamy posiedzenie. Bardzo państwa proszę o rozważenie możliwości zapisania się do pytań w późniejszym terminie. Zgłoszenia na pewno będą otwarte jeszcze przez ponad 2 godziny – w czasie trwania exposé i wystąpień klubowych. Ze względu na szacownych gości, którzy nam dzisiaj towarzyszą, nie będę opóźniał rozpoczęcia posiedzenia bardziej niż do godz. 10.15.</utt>
<utt t="reaction">Chwila przerwy</utt>
<utt t="norm">Wznawiam posiedzenie. Szanowni Państwo! Witam marszałka Senatu Rzeczypospolitej Polskiej panią Małgorzatę Kidawa-Błońską.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Serdecznie witam pana prezesa Rady Ministrów Donalda Tuska.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Witam obecnych na galerii byłych prezydentów Rzeczypospolitej Polskiej pana Lecha Wałęsę i pana Aleksandra Kwaśniewskiego.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Witam byłych marszałków Sejmu i Senatu oraz byłych premierów.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Witam bardzo licznie przybyły korpus dyplomatyczny.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Witam przedstawicieli Kościołów i związków wyznaniowych.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Witam wszystkich przedstawicieli organów i instytucji państwowych. Witam przedstawicieli wojska i służb mundurowych.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Witam także przedstawicieli samorządu terytorialnego, których też widzę na galerii. Cieszę się, że z nami dzisiaj, w tym uroczystym dniu, jesteście.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">Witam wszystkich przybyłych gości. Na sekretarzy dzisiejszych obrad powołuję posłów Pawła Bliźniuka oraz Aleksandrę Karolinę Wiśniewską. Protokół i listę mówców prowadzić będzie poseł Aleksandra Karolina Wiśniewska.</utt>
<utt t="reaction">Wypowiedź poza mikrofonem</utt>
<utt t="norm">Dziękuję serdecznie. Odwzajemniam się państwu miłym powitaniem. Sejm, w trybie art. 154 ust. 3 konstytucji, wybrał pana Donalda Tuska na prezesa Rady Ministrów. Prezes Rady Ministrów pan Donald Tusk zgłosił gotowość przedstawienia programu działania Rady Ministrów oraz proponowanego przez niego składu Rady Ministrów. W związku z tym, po uzyskaniu jednolitej opinii Konwentu Seniorów, podjąłem decyzję o uzupełnieniu porządku dziennego o ten właśnie punkt. Prezydium Sejmu proponuje, aby Sejm w dyskusji nad tym punktem porządku dziennego wysłuchał 10-minutowych oświadczeń w imieniu klubów i 5-minutowego oświadczenia w imieniu koła. Jeżeli nie usłyszę sprzeciwu, będę uważał, że Sejm tę propozycję przyjął. Sprzeciwu nie słyszę. Wnioski formalne zgłoszono dwa. Jako pierwszy pan poseł Grzegorz Braun z Konfederacji, a później pan poseł Antoni Macierewicz z Prawa i Sprawiedliwości.</utt>
<utt t="reaction">Oklaski</utt>
</speech>
<speech speaker="Poseł Grzegorz Braun">
<utt t="norm">Szczęść Boże! Wysoka Izbo! Panie Marszałku! Kiedy zamykał pan wczorajszy dzień ciągle jeszcze 1. posiedzenia Sejmu X kadencji, z tego miejsca bez trybu pan prezes, premier, naczelnik Kaczyński wygłosił zdanie, które nie miało charakteru ocennego. On stwierdzał fakt: Donald Tusk agentem niemieckim. Rozumiem, że pan premier, prezes, naczelnik, w swoim czasie szef komitetu bezpieki rządu własnej kreacji nie dopełnił obowiązków, a może przekroczył uprawnienia. Być może wszedł w posiadanie informacji, do których nie miał prawa docierać, a być może nie dopełnił obowiązków, ponieważ, jak rozumiem, nie uruchomił żadnych procedur, które by doprowadziły do zbadania</utt>
<utt t="reaction">Dzwonek</utt>
<utt t="norm">i przykładnego napiętnowania przypadku zdrady narodowej. Panowie Kamiński, Wąsik et consortes również…</utt>
<utt t="interrupt" by="Głos z sali">Czas.</utt>
<utt t="norm">Sprawa jest ważna, panie marszałku.</utt>
</speech>
<speech speaker="Marszałek Szymon Hołownia">
<utt t="norm">Tak, panie pośle, ale…</utt>
</speech>
<speech speaker="Poseł Grzegorz Braun">
<utt t="norm">…najwyraźniej nie dopełnili obowiązków. Z tego miejsca padały już podobne zdania…</utt>
<utt t="interrupt" by="Głos z sali">A w jakiej sprawie ten wniosek formalny?</utt>
<utt t="norm">…i powinni byli siedzieć – albo Milczanowski, albo Oleksy, albo Morawiecki, albo pan redaktor Szymowski.</utt>
</speech>
<speech speaker="Marszałek Szymon Hołownia">
<utt t="norm">Panie pośle, proszę o konkluzję.</utt>
</speech>
<speech speaker="Poseł Grzegorz Braun">
<utt t="norm">Ktoś powinien wreszcie siedzieć. To nie jest sprawa…</utt>
</speech>
<speech speaker="Marszałek Szymon Hołownia">
<utt t="norm">Panie pośle…</utt>
</speech>
<speech speaker="Poseł Grzegorz Braun">
<utt t="norm">To nie jest sprawa, panie marszałku, jak był pan łaskaw to dziś podsumować, prywatnego chamstwa i braku zdolności do przestrzegania norm współżycia społecznego.</utt>
<utt t="interrupt" by="Głos z sali">Ha, ha, ha!</utt>
<utt t="interrupt" by="Poseł Barbara Bartuś">I kto to mówi?</utt>
<utt t="norm">Proszę nie sprowadzać tego na tory prywatnego konfliktu dwóch zgryźliwych tetryków. Mówmy o sprawach…</utt>
<utt t="reaction">Marszałek wyłącza mikrofon, poseł przemawia przy wyłączonym mikrofonie</utt>
<utt t="norm">…państwa w sposób…</utt>
<utt t="reaction">Poruszenie na sali</utt>
</speech>
<speech speaker="Marszałek Szymon Hołownia">
<utt t="norm">Panie pośle, przekroczył pan czas dwukrotnie. Naprawdę nie mogę dłużej tego tolerować. Serdecznie panu posłowi dziękuję.</utt>
<utt t="interrupt" by="Poseł Grzegorz Braun">Pytam: Kto będzie siedział? Kto będzie siedział?</utt>
<utt t="interrupt" by="Głos z sali">Ty będziesz siedział.</utt>
<utt t="interrupt" by="Głos z sali">Siadaj!</utt>
<utt t="norm">Dowiemy się w swoim czasie. Na razie proszę, żeby to pan usiadł.</utt>
<utt t="reaction">Oklaski</utt>
<utt t="norm">A teraz zapraszam pana posła Antoniego Macierewicza.</utt>
<utt t="reaction">Wypowiedź poza mikrofonem</utt>
<utt t="norm">Siedzi, ale nie w tym sensie siedzi.</utt>
<utt t="interrupt" by="Głos z sali">Będzie internowany.</utt>
<utt t="norm">Proszę o spokój, panie pośle.</utt>
</speech>
</content>
</session>
